spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: rice8828

  # JPA Settings
#    jpa.hibernate.ddl_auto: update
    jpa.hibernate.ddl_auto: create